/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function deidentify2DDicom(srcDcmPath: string, dstDcmPath: string): number

export declare function exportParsedStandardDirectory(jsonUtf8Content: string, exportRootDir: string, exportType: number): string
