/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123103-g5315d12139-20260302"
#endif /* AVUTIL_FFVERSION_H */
